### ISSUE TITLE
cursor hold doesn't run jshint

### ISSUE THREAD

**Issue by bounceme** [osyo-manga/vim-watchdogs#26]
```
let g:watchdogs_check_BufWritePost_enable = 1
let g:watchdogs_check_CursorHold_enable = 1
let g:watchdogs_check_BufWritePost_enables = {
			\ "javascript" : 1
			\}
let g:watchdogs_check_CursorHold_enables = {
			\ 'javascript': 1,
			\}
let g:quickrun_config = {
			\	"watchdogs_checker/_" : {
			\   'outputter/quickfix/open_cmd' : '',
			\	},
			\}
call watchdogs#setup(g:quickrun_config)
```

I've installed all required plugins and the recommended ones.The bufwrite check takes about 5 seconds and cursor hold doesn't seem to work at all.

**Comment by osyo-manga** [comment]
hmm...
Please execute `:WatchdogsRun` command, and check `'updatetime'` option.

**Comment by bounceme** [comment]
update time is 4000,which is the default I think since I haven't changed it

**Comment by osyo-manga** [comment]
hmm...
jshint work in my vim.

**Comment by bounceme** [comment]
Hey,after google translating the doc now I know this only makes 1 cursor hold check after each save,so i will close this,Thanks
